module.exports = {
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  MONGODB_URI: process.env.MONGODB_URI,
  COOKIE_KEY: process.env.COOKIE_KEY,
  STRIPE_PUB_KEY: process.env.STRIPE_PUB_KEY,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY
};
